"""add context in request and fix value in parameters

Revision ID: 627386bf30b9
Revises: 93a715dfb545
Create Date: 2025-02-10 15:32:56.114782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '627386bf30b9'
down_revision: Union[str, None] = '93a715dfb545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('context', sa.Text(), nullable=True))

    # 2️⃣ Заполняем существующие строки значением по умолчанию (например, пустая строка)
    op.execute("UPDATE request SET context = '' WHERE context IS NULL")

    # 3️⃣ Делаем колонку `context` NOT NULL после обновления данных
    op.alter_column('request', 'context', nullable=False)

    op.alter_column('parameter', 'value',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'context')
    op.alter_column('parameter', 'value',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
