"""replace author_id with user_id

Revision ID: 93a715dfb545
Revises: d4a45611a6f7
Create Date: 2025-02-09 22:49:17.968787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93a715dfb545'
down_revision: Union[str, None] = 'd4a45611a6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('user_id', sa.UUID(), nullable=False))
    op.drop_column('comment', 'author_id')
    op.add_column('rating', sa.Column('user_id', sa.UUID(), nullable=False))
    op.drop_column('rating', 'author_id')
    op.add_column('request', sa.Column('user_id', sa.UUID(), nullable=False))
    op.drop_column('request', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('request', 'user_id')
    op.add_column('rating', sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('rating', 'user_id')
    op.add_column('comment', sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('comment', 'user_id')
    # ### end Alembic commands ###
