x-app: &app
  env_file:
    - ./.env
  restart: always
  platform: linux/amd64
  networks:
    - skolstream_network

services:
  postgres:
    image: postgres:14
    container_name: report-postgres
    <<: *app
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      TZ: "Europe/Moscow"
      PGTZ: "Europe/Moscow"

  redis:
    image: redis:6
    container_name: report-redis
    <<: *app
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./app
    container_name: report-app
    <<: *app
    volumes:
      - ./app:/usr/src/app/
    ports:
      - "8123:8000"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  ollama:
    image: ollama/ollama
    container_name: report-ollama
    <<: *app
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama

volumes:
  postgres_volume:
  redis_volume:

networks:
  skolstream_network:
    external: true