x-app: &app
  env_file:
    - ./.env
  restart: always
  platform: linux/amd64

services:
  postgres:
    image: postgres:14
    container_name: report-postgres
    <<: *app
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      TZ: "Europe/Moscow"
      PGTZ: "Europe/Moscow"

  redis:
    image: redis:6
    container_name: report-redis
    <<: *app
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: aleksioprime/progress-report-app:latest
    container_name: report-app
    <<: *app
    ports:
      - "8123:8000"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  front:
    image: aleksioprime/progress-report-front:latest
    container_name: report-front
    <<: *app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/www/certbot:/var/www/certbot
      - /root/repgen/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      app:
        condition: service_started

  ollama:
    image: ollama/ollama
    container_name: report-ollama
    <<: *app
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama

  watchtower:
    image: containrrr/watchtower
    container_name: report-watchtower
    <<: *app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup


volumes:
  postgres_volume:
  redis_volume: