name: Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push backend image
      run: |
        docker build -t aleksioprime/progress-report-app:latest ./app
        docker push aleksioprime/progress-report-app:latest

    - name: Build and push frontend image
      run: |
        docker build -t aleksioprime/progress-report-front:latest ./front
        docker push aleksioprime/progress-report-front:latest

    - name: Run backend tests
      run: |
        echo "Тесты бэкенда пока отключены. Возвращаем успешный статус."

    - name: Run frontent tests
      run: |
        echo "Тесты фронтенда пока отключены. Возвращаем успешный статус."
